import { makeStyles } from '@material-ui/core/styles';

export default makeStyles((theme) => ({
  link: {
    // width: 125.83,
    color: '#979797',
    fontSize: 14,
    fontFamily: 'Poppins',
    textDecoration: 'none',
    lineHeight: 'auto',
    fontWeight: '400',
    wordWrap: 'break-word',
  },
  container: {
    height: '110%',
    backgroundColor: '#F9F9F9',
    alignItems: 'center',
    padding: '5rem',
    marginTop: '15rem',
    // minHeight: '100vh',
  },
  content: {
    height: 404,
    paddingTop: 120,
    paddingBottom: 120,
    paddingLeft: 120,
    paddingRight: 120,
    display: 'inline-flex',
    flexDirection: 'row',
    justifyContent: 'start',
    alignItems: 'start',
    width: '100%',
    flexWrap: 'no-wrap',
    background: 'blue',
  },
  title: {
    // width: 119.32,
    color: '#161414',
    fontSize: 18,
    fontFamily: 'Poppins',
    fontWeight: '500',
    lineHeight: 'auto',
    wordWrap: 'break-word',
  },

  list: {
    alignItems: 'flex-start',
    justifyContent: 'start',
  },
  ListItem: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  image: {
    width: '100px',
  },
  text: {
    width: '80%',
    color: '#979797',
    fontSize: 14,
    fontFamily: 'Poppins',
    fontWeight: '400',
    wordWrap: 'break-word',
  },
  content: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  linkContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  links: {
    // width: 505.5,
    // height: 164,
    width: '100%',
    display: 'inline-flex',
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    flexWrap: 'nowrap',
    gap: 60,
  },
  Brand: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    gap: 10,
  },
  Divider: {
    backgroundColor: 'black',
    color: 'black',
    width: '100%',
  },
  gutter: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'space-between',
  },
  gutterText: {
    color: 'black',
  },
}));
